# Generated by Django 5.2.12 on 2026-05-04 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("color", models.CharField(default="#FFFF00", max_length=7)),
                ("weight", models.FloatField(default=0)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("unit_of_measurement", models.TextField(blank=True)),
                ("base_target", models.TextField(blank=True)),
                ("stretch_target", models.TextField(blank=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("base_deadline", models.DateField(blank=True, null=True)),
                ("stretch_deadline", models.DateField(blank=True, null=True)),
                ("completion_level", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("on_track", "On Track"),
                            ("behind", "Behind Schedule"),
                            ("ahead", "Ahead of Schedule"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Progress update and what is pending"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="tasks.goal",
                    ),
                ),
            ],
        ),
    ]
