# Generated by Django 5.2.12 on 2026-05-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="ai_insight",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="task",
            name="ai_insight_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
