# Generated by Django 5.2.12 on 2026-05-14 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_taskupdate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="ai_insight",
        ),
        migrations.RemoveField(
            model_name="task",
            name="ai_insight_at",
        ),
    ]
